---
title: "Untitled"
author: "Christopher Crowe"
date: "December 1, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(googledrive)
library(httr)
library(tidyverse)
```
 
```{r check_one}
drive_download(as_id("https://drive.google.com/open?id=12qBx-FbPIKAA_aQr5JoMR9ehvpmRrbWN"), path = "./shiny/34315-0001-Data.rda", overwrite = TRUE)
drive_download(as_id("https://drive.google.com/open?id=1BLislRpc8OTvtYEw8118WKKLkVuHhV6C"), path = "./shiny/37105-0001-Data.rda", overwrite = TRUE)
drive_download(as_id("https://drive.google.com/open?id=1gj53tdb5RHhX5NPDv2eyBqfgEBPAc42G", path = "./shiny/37106-0001-Data.rda", overwrite = TRUE))
 
# Save the data outside the shiny folder for use elsewhere in the website
drive_download(as_id("https://drive.google.com/open?id=12qBx-FbPIKAA_aQr5JoMR9ehvpmRrbWN", path = "./34315-0001-Data.rda", overwrite = TRUE))
drive_download(as_id("https://drive.google.com/open?id=1BLislRpc8OTvtYEw8118WKKLkVuHhV6C", path = "./37105-0001-Data.rda", overwrite = TRUE))
drive_download(as_id("https://drive.google.com/open?id=1gj53tdb5RHhX5NPDv2eyBqfgEBPAc42G", path = "./37106-0001-Data.rda", overwrite = TRUE))
```

