---
title: "Data Science Proposal"
author: "Christopher Crowe, Diana Ballesteros, & Tanvi Jain"
date: "November 5, 2018"
output: github_document
---

**Group Members:**

* Diana Ballesteros Gonzalez (uni: deg2163) 
* Chris Crowe (uni: clc2229) 
* Tanvi Jain (uni: tj2383)

**Tentative project title:** 

* Analysis of a Longitudinal Study on Aging Conducted in Ireland 

**The motivation for this project:**

* This project aims to look at the effect of sociodemographic indicators on mental health among a cohort of Irish residents aged 50+ yrs.

**The anticipated data sources:**

* The Irish Longitudinal Study on Ageing (TILDA) Waves 1, 2, and 3
* https://www.icpsr.umich.edu/icpsrweb/ICPSR/series/726

**The intended final products:** 

* Descriptive statistics in the form of tables and plots that provide information on our project objective
* Final products include: report and webpage with screencast

**The planned analyses / visualizations / coding challenges:**

* ICD-10 code distribution for Wave 2 and 3 (potentially use shiny)
* Will look at key indicators such as: retired status, marital status (CS006), education (DM001), weight in kg (WEIGHT), mini mental state examination(COGMMSE_HA), BMI(FRBMI), loneliness(MHucla_loneliness), total financial assets(INCASSassets5, quintiles),  and number of close relatives or friends (SOCsocnet), self-rated physical health (PH001) and mental health (PH002)

Visualizations:

* ICD-10: bar graph of proportions of each ICD-10 code to determine which ICD-10 diagnosis accounts for the greatest burden of disease in our population. We can potentially facet by sex to see if the burden is different for males and females. 
* Loneliness: spaghetti plot of loneliness over time for males who were widowed at baseline.
* Physical & Mental/Emotional Health: hexagonal heatmap of self-rated physical health vs.  mental/emotional health among all individuals in Wave 3.
* Quality of Life: density plots of the distribution of total scores on the CASP-19 by age group in Wave 2. 

All: 

* physical activity(IPAQexercise3, low/moderate/high)
* age(AGE)
* employment status(employ in Waves 2&3 and WE001 in Wave 1)

Wave 1: 

* sex(SEX)
* income (INCASSETSweklyHHdisy)

Wave 3: 

* number of close relatives or friends (SOCsocnet)



* Physical activity levels (IPAQexercise3, low/moderate/high) changes over time 
* Comparing them to the outcome of interest: quality of life (MHcasp19_total) 
* Coding challenges: combining data from multiple waves with different variable names 

**The planned timeline:**

* Nov 12th-16th: Project review meeting 
* Week of Nov 19th: Meet up to work on the report and website  
* Week of Nov 26th: Make any last edits on the report and website and begin screencast 
* December 3rd: Add screencast to website and complete final edits 
* Dec 6th: Report, webcast, and web page due 