---
title: "Exploratory Analyses for The Irish Longitudinal Study on Ageing (TILDA)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny

---

```{r setup, include=FALSE}
## Load required libraries
library(flexdashboard)
library(viridis)
library(plotly)
library(dplyr)
library(tidyverse)


load("../data/Wave 1/DS0001/34315-0001-Data.rda")
load("../data/Wave 2/DS0001/37105-0001-Data.rda")
load("../data/Wave 3/DS0001/37106-0001-Data.rda")

## Create functions to clean variables
clean_wave = function(x) {
  
  x %>% 
    mutate(
      wave = case_when(
        str_detect(wave, "_1$") ~ 1,
        str_detect(wave, "_2$") ~ 2,
        str_detect(wave, "_3$") ~ 3
    )
  )
  
}
clean_physical = function(x) {
  
  x %>% 
    mutate(
      physical = case_when(
        physical_value == "(1) Excellent" ~ "Excellent", 
        physical_value == "(2) Very good" ~ "Very Good",
        physical_value == "(3) Good" ~ "Good", 
        physical_value == "(4) Fair" ~ "Fair", 
        physical_value == "(5) Poor" ~ "Poor",
        physical_value == "(01) Excellent" ~ "Excellent", 
        physical_value == "(02) Very Good" ~ "Very Good",
        physical_value == "(03) Good" ~ "Good", 
        physical_value == "(04) Fair" ~ "Fair", 
        physical_value == "(05) Poor" ~ "Poor"),
      physical = factor(physical, levels = c("Poor", "Fair", "Good", "Very Good", "Excellent"))
    )
  
}
clean_mental = function(x) {
  
  x %>% 
    mutate(
      mental = case_when(
        mental_value == "(1) Excellent" ~ "Excellent", 
        mental_value == "(2) Very good" ~ "Very Good",
        mental_value == "(3) Good" ~ "Good", 
        mental_value == "(4) Fair" ~ "Fair", 
        mental_value == "(5) Poor" ~ "Poor",
        mental_value == "(01) Excellent" ~ "Excellent", 
        mental_value == "(02) Very Good" ~ "Very Good",
        mental_value == "(03) Good" ~ "Good", 
        mental_value == "(04) Fair" ~ "Fair", 
        mental_value == "(05) Poor" ~ "Poor"),
      mental = factor(mental, levels = c("Poor", "Fair", "Good", "Very Good", "Excellent"))
    )
}
clean_marital = function(x) {
  
  x %>% 
    mutate(
      marital = case_when(
        CS006 == "(1) Married" ~ "Married",
        CS006 == "(2) Living with a partner as if married" ~ "Living w/ Partner",
        CS006 == "(3) Single (never married)" ~ "Never married",
        CS006 == "(4) Separated" ~ "Separated",
        CS006 == "(5) Divorced" ~ "Divorced",
        CS006 == "(6) Widowed" ~ "Widowed"),
      marital = factor(marital, levels = c("Married", "Living w/ Partner", "Never married",
                                           "Separated", "Divorced", "Widowed"))
    )
  
}
clean_sex = function(x) {
  
   x %>% 
    mutate(
      sex = case_when(
        SEX == "(1) Male" ~ "Male",
        SEX == "(2) Female" ~ "Female")
    )
  
}


```


```{r}

## Assign data from each wave to a new object where common variable names are given unique names
wave_1_data = da34315.0001 %>% 
  mutate(MHUCLA_LONELINESS_1 = MHUCLA_LONELINESS,
         PH001_1 = PH001,
         PH002_1 = PH002)
 
wave_2_data = da37105.0001 %>% 
  mutate(MHUCLA_LONELINESS_2 = MHUCLA_LONELINESS,
         PH001_2 = PH001,
         PH002_2 = PH002
  )
      
wave_3_data = da37106.0001 %>% 
  mutate(MHUCLA_LONELINESS_3 = MHUCLA_LONELINESS,
         PH001_3 = PH001,
         PH002_3 = PH002
  )
## Data for Physical Health vs. Mental Health
## Tidy data for self-report physical health
overall_1 = wave_1_data %>%  
  merge(wave_2_data, by = "ID") %>% 
  merge(wave_3_data, by = "ID") %>% 
  select(PH001_1, PH001_2, PH001_3, SEX.x, CS006, ID) %>% 
  gather(wave, physical_value, PH001_1:PH001_3) %>% 
  clean_wave()
  
## Tidy data for self-report mental health
overall_2 = wave_1_data %>%  
  merge(wave_2_data, by = "ID") %>% 
  merge(wave_3_data, by = "ID") %>% 
  select(PH002_1, PH002_2, PH002_3, SEX.x, CS006, ID) %>% 
  gather(wave, mental_value, PH002_1:PH002_3) %>% 
  clean_wave()
## Tidy data for loneliness
overall_3 = wave_1_data %>%  
  merge(wave_2_data, by = "ID") %>% 
  merge(wave_3_data, by = "ID") %>% 
  select(MHUCLA_LONELINESS_1, MHUCLA_LONELINESS_2, MHUCLA_LONELINESS_3, SEX.x, CS006, ID) %>% 
  gather(wave, loneliness_value, MHUCLA_LONELINESS_1:MHUCLA_LONELINESS_3) %>% 
  clean_wave()
## Tidy data for ICD codes
overall_4 = wave_1_data %>%  
  merge(wave_3_data, by = "ID") %>% 
  select(ICD10_01:ICD10_16, ID, SEX.x, CS006) %>% 
  mutate(SEX = SEX.x) %>% 
  clean_sex() %>% 
  clean_marital() %>% 
  select(-SEX.x, -SEX, -CS006)
 
  
## Combine data for self-report physical and mental health, apply functions to create consistent, clean labels for variables
final = overall_1 %>% 
  merge(overall_2, by = c("ID", "wave")) %>% 
  merge(overall_3, by = c("ID", "wave")) %>% 
  select(ID, wave, SEX.x, CS006.x, physical_value, mental_value, loneliness_value) %>% 
  clean_physical() %>% 
  clean_mental() %>% 
  mutate(
    CS006 = CS006.x,
    SEX = SEX.x
  ) %>% 
  clean_marital() %>% 
  clean_sex() %>% 
  select(-physical_value, -mental_value, -SEX, -CS006, -SEX.x, -CS006.x)
## Prepare data for loneliness plot
plot_3 = 
  wave_1_data %>% 
  merge(wave_2_data, by = "ID") %>% 
  merge(wave_3_data, by = "ID") %>% 
  select(SEX.x, CS006, ID, MHUCLA_LONELINESS_1, MHUCLA_LONELINESS_2, MHUCLA_LONELINESS_3)  %>% 
  mutate(
    SEX = SEX.x
  ) %>% 
  clean_sex() %>% 
  clean_marital() %>% 
  select(-SEX.x, -CS006, -SEX)
## Prepare data for ICD plot
  
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
sex_choice = final %>% distinct(sex) %>% pull()
marital_choice = final %>% distinct(marital) %>% pull()
wave_choice = final %>% distinct(wave) %>% pull()
radioButtons("wave_choice", label = h3("Choose wave"),
    choices = wave_choice,
    selected = 1)
radioButtons("sex_choice", label = h3("Choose sex"),
    choices = sex_choice, 
    selected = "Male")
radioButtons("marital_choice", label = h3("Choose marital status"),
    choices = marital_choice, 
    selected = "Married")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Proportion of Incident Disease Burden in Wave 3 Attributable to Specified Disease

```{r}
renderPlotly({
icd_data = overall_4 %>% 
  filter(sex == input$sex_choice & marital == input$marital_choice) %>% 
  summarize(total_01 = sum(ICD10_01), total_02 = sum(ICD10_02), total_03 = sum(ICD10_03), 
            total_04 = sum(ICD10_04), total_05 = sum(ICD10_05), total_06 = sum(ICD10_06), 
            total_07 = sum(ICD10_07), total_08 = sum(ICD10_08), total_09 = sum(ICD10_09),
            total_10 = sum(ICD10_10), total_11 = sum(ICD10_11), total_12 = sum(ICD10_12),
            total_13 = sum(ICD10_13), total_14 = sum(ICD10_14), total_15 = sum(ICD10_15),
            total_16 = sum(ICD10_16)) %>% 
  gather(key = icd_code, value = total, total_01:total_16) %>% 
  separate(icd_code, into = c("total_char","icd_code"), sep = "_") %>% 
  select(-total_char) %>% 
  mutate(burden = total/sum(total)*100) %>% 
  mutate(disease = case_when(
    icd_code == "01" ~ "Infectious diseases",
    icd_code == "02" ~ "Neoplasms",
    icd_code == "03" ~ "Blood diseases",
    icd_code == "04" ~ "Nutritional/metabolic diseases",
    icd_code == "05" ~ "Mental/behavioral disorders",
    icd_code == "06" ~ "Nervous system diseases",
    icd_code == "07" ~ "Eye diseases",
    icd_code == "08" ~ "Ear diseases",
    icd_code == "09" ~ "Circulatory system diseases",
    icd_code == "10" ~ "Respiratory system diseases",
    icd_code == "11" ~ "Digestive system diseases",
    icd_code == "12" ~ "Skin diseases",
    icd_code == "13" ~ "Musculoskeletal system diseases",
    icd_code == "14" ~ "Genitourinary system diseases",
    icd_code == "15" ~ "Perinatal conditions",
    icd_code == "16" ~ "Congenital malformations"
  ))
icd_plot = 
  icd_data %>% 
  ggplot(aes(x = reorder(disease, -burden), y = burden)) +
  geom_bar(stat = "identity") + 
  labs(
    x = "Disease",
    y = "Percentage"
  ) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 65, size = 7))
ggplotly(icd_plot)
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Self-Rated Mental vs. Physical Health Status

```{r}
renderPlotly({
  
  plot_1 = final %>%
  filter(sex == input$sex_choice & marital == input$marital_choice & wave == input$wave_choice ) %>% 
  ggplot(aes(x = physical, y = mental, color = ..n..)) +
  geom_count(alpha = 0.8) +
  labs(
    x = "Self-Rated Physical Health",
    y = "Self-Rated Mental Health"
  ) +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 65, hjust = 1))
ggplotly(plot_1)
})
```

### Trends in Loneliness Scores by Baseline Loneliness Score

```{r}
renderPlotly({
for (i in 0:10) {
  
  data = plot_3 %>% 
  filter(MHUCLA_LONELINESS_1 == i & sex == input$sex_choice & marital == input$marital_choice) %>% 
  select(ID, MHUCLA_LONELINESS_1, MHUCLA_LONELINESS_2, MHUCLA_LONELINESS_3) %>% 
  gather(key = wave, value = loneliness_value, MHUCLA_LONELINESS_1:MHUCLA_LONELINESS_3) %>% 
  clean_wave() %>% 
  filter(loneliness_value != "NA")
  
  name = paste("baseline_loneliness_", i, sep = "")
  assign(name, data )
  
}
plot_3 = baseline_loneliness_0 %>% 
  ggplot(aes(x = wave, y = loneliness_value)) +
  geom_smooth(se = FALSE) +
  geom_smooth(data = baseline_loneliness_1, aes(x = wave, y = loneliness_value), se = FALSE) +
  geom_smooth(data = baseline_loneliness_2, aes(x = wave, y = loneliness_value), se = FALSE) +
  geom_smooth(data = baseline_loneliness_3, aes(x = wave, y = loneliness_value), se = FALSE) +
  geom_smooth(data = baseline_loneliness_4, aes(x = wave, y = loneliness_value), se = FALSE) +
  geom_smooth(data = baseline_loneliness_5, aes(x = wave, y = loneliness_value), se = FALSE) +
  geom_smooth(data = baseline_loneliness_6, aes(x = wave, y = loneliness_value), se = FALSE) +
  geom_smooth(data = baseline_loneliness_7, aes(x = wave, y = loneliness_value), se = FALSE) +
  geom_smooth(data = baseline_loneliness_8, aes(x = wave, y = loneliness_value), se = FALSE) +
  geom_smooth(data = baseline_loneliness_9, aes(x = wave, y = loneliness_value), se = FALSE) +
  geom_smooth(data = baseline_loneliness_10, aes(x = wave, y = loneliness_value), se = FALSE) +
  scale_y_continuous(breaks = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)) +
  scale_x_continuous(breaks = c(1, 2, 3)) +
  theme_bw() +
  labs(
    x = "Wave",
    y = "UCLA Loneliness Score"
  )
ggplotly(plot_3)
})
```